package channel

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/url"
	"regexp"
	"strings"
	"sync"
	"time"

	common2 "github.com/QuantumNous/new-api/common"
	appconstant "github.com/QuantumNous/new-api/constant"
	"github.com/QuantumNous/new-api/logger"
	"github.com/QuantumNous/new-api/relay/common"
	"github.com/QuantumNous/new-api/relay/constant"
	"github.com/QuantumNous/new-api/relay/helper"
	"github.com/QuantumNous/new-api/service"
	"github.com/QuantumNous/new-api/setting/operation_setting"
	"github.com/QuantumNous/new-api/types"

	"github.com/bytedance/gopkg/util/gopool"
	"github.com/gin-gonic/gin"
	"github.com/gorilla/websocket"
)

func SetupApiRequestHeader(info *common.RelayInfo, c *gin.Context, req *http.Header) {
	if info.RelayMode == constant.RelayModeAudioTranscription || info.RelayMode == constant.RelayModeAudioTranslation {
		// multipart/form-data
	} else if info.RelayMode == constant.RelayModeRealtime {
		// websocket
	} else {
		req.Set("Content-Type", c.Request.Header.Get("Content-Type"))
		req.Set("Accept", c.Request.Header.Get("Accept"))
		if info.IsStream && c.Request.Header.Get("Accept") == "" {
			req.Set("Accept", "text/event-stream")
		}
	}
}

const clientHeaderPlaceholderPrefix = "{client_header:"

const (
	headerPassthroughAllKey        = "*"
	headerPassthroughRegexPrefix   = "re:"
	headerPassthroughRegexPrefixV2 = "regex:"
)

var passthroughSkipHeaderNamesLower = map[string]struct{}{
	// RFC 7230 hop-by-hop headers.
	"connection":          {},
	"keep-alive":          {},
	"proxy-authenticate":  {},
	"proxy-authorization": {},
	"te":                  {},
	"trailer":             {},
	"transfer-encoding":   {},
	"upgrade":             {},

	"cookie": {},

	// Additional headers that should not be forwarded by name-matching passthrough rules.
	"host":            {},
	"content-length":  {},
	"accept-encoding": {},

	// Do not passthrough credentials by wildcard/regex.
	"authorization":  {},
	"x-api-key":      {},
	"x-goog-api-key": {},

	// GPUStack 内部路由头，绝不能接受客户端传入。
	//
	// 我们自己**不发**它（实例亲和走的是改写目标 URL 直连，见
	// gpustackAffinityRewriteURL）。挡在这里是因为它是 GPUStack 网关「网关 → worker」
	// 的内部信号：网关的 set-model-pre-route 插件把选中的 cluster 名写进这个头，
	// worker 的 set_port_from_model_name 据此把请求转给本机的某个实例。客户端传进来
	// 的值会让这两端不一致——请求被负载均衡送到 worker X，头却说实例在 worker Y，
	// worker X 查不到就 404。2026-09-15 实测:放开网关侧的剥离后 3/6 的请求 404。
	// 网关自己也会剥（gpustack 的 transformer 插件），这里再挡一道是为了不依赖
	// 上游的配置：前者是代码保证，后者是部署约定。
	"x-gpustack-model-instance": {},

	// WebSocket handshake headers are generated by the client/dialer.
	"sec-websocket-key":        {},
	"sec-websocket-version":    {},
	"sec-websocket-extensions": {},
}

var headerPassthroughRegexCache sync.Map // map[string]*regexp.Regexp

func getHeaderPassthroughRegex(pattern string) (*regexp.Regexp, error) {
	pattern = strings.TrimSpace(pattern)
	if pattern == "" {
		return nil, errors.New("empty regex pattern")
	}
	if v, ok := headerPassthroughRegexCache.Load(pattern); ok {
		if re, ok := v.(*regexp.Regexp); ok {
			return re, nil
		}
		headerPassthroughRegexCache.Delete(pattern)
	}
	compiled, err := regexp.Compile(pattern)
	if err != nil {
		return nil, err
	}
	actual, _ := headerPassthroughRegexCache.LoadOrStore(pattern, compiled)
	if re, ok := actual.(*regexp.Regexp); ok {
		return re, nil
	}
	return compiled, nil
}

func IsHeaderPassthroughRuleKey(key string) bool {
	return isHeaderPassthroughRuleKey(key)
}
func isHeaderPassthroughRuleKey(key string) bool {
	key = strings.TrimSpace(key)
	if key == "" {
		return false
	}
	if key == headerPassthroughAllKey {
		return true
	}
	lower := strings.ToLower(key)
	return strings.HasPrefix(lower, headerPassthroughRegexPrefix) || strings.HasPrefix(lower, headerPassthroughRegexPrefixV2)
}

func shouldSkipPassthroughHeader(name string) bool {
	name = strings.TrimSpace(name)
	if name == "" {
		return true
	}
	lower := strings.ToLower(name)
	if _, ok := passthroughSkipHeaderNamesLower[lower]; ok {
		return true
	}
	return false
}

func applyHeaderOverridePlaceholders(template string, c *gin.Context, apiKey string) (string, bool, error) {
	trimmed := strings.TrimSpace(template)
	if strings.HasPrefix(trimmed, clientHeaderPlaceholderPrefix) {
		afterPrefix := trimmed[len(clientHeaderPlaceholderPrefix):]
		end := strings.Index(afterPrefix, "}")
		if end < 0 || end != len(afterPrefix)-1 {
			return "", false, fmt.Errorf("client_header placeholder must be the full value: %q", template)
		}

		name := strings.TrimSpace(afterPrefix[:end])
		if name == "" {
			return "", false, fmt.Errorf("client_header placeholder name is empty: %q", template)
		}
		if c == nil || c.Request == nil {
			return "", false, fmt.Errorf("missing request context for client_header placeholder")
		}
		clientHeaderValue := c.Request.Header.Get(name)
		if strings.TrimSpace(clientHeaderValue) == "" {
			return "", false, nil
		}
		// Do not interpolate {api_key} inside client-supplied content.
		return clientHeaderValue, true, nil
	}

	if strings.Contains(template, "{api_key}") {
		template = strings.ReplaceAll(template, "{api_key}", apiKey)
	}
	if strings.TrimSpace(template) == "" {
		return "", false, nil
	}
	return template, true, nil
}

// processHeaderOverride applies channel header overrides, with placeholder substitution.
// Supported placeholders:
//   - {api_key}: resolved to the channel API key
//   - {client_header:<name>}: resolved to the incoming request header value
//
// Header passthrough rules (keys only; values are ignored):
//   - "*": passthrough all incoming headers by name (excluding unsafe headers)
//   - "re:<regex>" / "regex:<regex>": passthrough headers whose names match the regex (Go regexp)
//
// Passthrough rules are applied first, then normal overrides are applied, so explicit overrides win.
func processHeaderOverride(info *common.RelayInfo, c *gin.Context) (map[string]string, error) {
	headerOverride := make(map[string]string)
	if info == nil {
		return headerOverride, nil
	}

	headerOverrideSource := common.GetEffectiveHeaderOverride(info)

	passAll := false
	var passthroughRegex []*regexp.Regexp
	if !info.IsChannelTest {
		for k := range headerOverrideSource {
			key := strings.TrimSpace(strings.ToLower(k))
			if key == "" {
				continue
			}
			if key == headerPassthroughAllKey {
				passAll = true
				continue
			}

			var pattern string
			switch {
			case strings.HasPrefix(key, headerPassthroughRegexPrefix):
				pattern = strings.TrimSpace(key[len(headerPassthroughRegexPrefix):])
			case strings.HasPrefix(key, headerPassthroughRegexPrefixV2):
				pattern = strings.TrimSpace(key[len(headerPassthroughRegexPrefixV2):])
			default:
				continue
			}

			if pattern == "" {
				return nil, types.NewError(fmt.Errorf("header passthrough regex pattern is empty: %q", k), types.ErrorCodeChannelHeaderOverrideInvalid)
			}
			compiled, err := getHeaderPassthroughRegex(pattern)
			if err != nil {
				return nil, types.NewError(err, types.ErrorCodeChannelHeaderOverrideInvalid)
			}
			passthroughRegex = append(passthroughRegex, compiled)
		}
	}

	if passAll || len(passthroughRegex) > 0 {
		if c == nil || c.Request == nil {
			return nil, types.NewError(fmt.Errorf("missing request context for header passthrough"), types.ErrorCodeChannelHeaderOverrideInvalid)
		}
		for name := range c.Request.Header {
			if shouldSkipPassthroughHeader(name) {
				continue
			}
			if !passAll {
				matched := false
				for _, re := range passthroughRegex {
					if re.MatchString(name) {
						matched = true
						break
					}
				}
				if !matched {
					continue
				}
			}
			value := strings.TrimSpace(c.Request.Header.Get(name))
			if value == "" {
				continue
			}
			headerOverride[strings.ToLower(strings.TrimSpace(name))] = value
		}
	}

	for k, v := range headerOverrideSource {
		if isHeaderPassthroughRuleKey(k) {
			continue
		}
		key := strings.TrimSpace(strings.ToLower(k))
		if key == "" {
			continue
		}

		str, ok := v.(string)
		if !ok {
			return nil, types.NewError(nil, types.ErrorCodeChannelHeaderOverrideInvalid)
		}
		if info.IsChannelTest && strings.HasPrefix(strings.TrimSpace(str), clientHeaderPlaceholderPrefix) {
			continue
		}

		value, include, err := applyHeaderOverridePlaceholders(str, c, info.ApiKey)
		if err != nil {
			return nil, types.NewError(err, types.ErrorCodeChannelHeaderOverrideInvalid)
		}
		if !include {
			continue
		}

		headerOverride[key] = value
	}
	return headerOverride, nil
}

func ResolveHeaderOverride(info *common.RelayInfo, c *gin.Context) (map[string]string, error) {
	return processHeaderOverride(info, c)
}

func applyHeaderOverrideToRequest(req *http.Request, headerOverride map[string]string) {
	if req == nil {
		return
	}
	for key, value := range headerOverride {
		req.Header.Set(key, value)
		// set Host in req
		if strings.EqualFold(key, "Host") {
			req.Host = value
		}
	}
}

// gpustackAffinityDialTimeout 直连实例前的拨号探测上限。
//
// 必须有：共享的 relay client 在 RELAY_TIMEOUT=0（默认）时既没有 Client.Timeout
// 也没有 Transport.DialContext（service/http_client.go），所以一个**黑洞**地址
// （丢包而不是拒连，例如路由不可达）会让请求卡到操作系统的 TCP connect 超时
// ——Linux 上约 130 秒——之后才走到回退。实例都在同一内网,正常拨号是亚毫秒级,
// 2 秒足够区分「能连」与「连不上」。
const gpustackAffinityDialTimeout = 2 * time.Second

// gpustackAffinityRewriteURL 把目标 URL 换成亲和选中的实例地址。
//
// 渠道 Base URL 的**路径前缀必须去掉**：实例的推理端口上只有裸 /v1/...。
// Base URL 形如 http://gw/gpustack 时，GetRequestURL 拼出的是
// http://gw/gpustack/v1/chat/completions，直接换 host 会得到
// http://<worker_ip>:<port>/gpustack/v1/chat/completions —— vLLM 不提供这个
// 路径，每个请求都 404。我们的部署里 Base URL 是纯 host:port，去不去前缀等价；
// 这里处理前缀是为了带前缀的渠道不被静默打到错误路径上。
//
// 返回空串表示本次不做亲和。
func gpustackAffinityRewriteURL(fullURL, baseURL string, c *gin.Context) string {
	if c == nil {
		return ""
	}
	target := common2.GetContextKeyString(c, appconstant.ContextKeyGPUStackInstanceBaseURL)
	if target == "" {
		return ""
	}
	orig, err := url.Parse(fullURL)
	if err != nil {
		return ""
	}
	t, err := url.Parse(target)
	if err != nil || t.Host == "" {
		return ""
	}
	if base, err := url.Parse(strings.TrimSpace(baseURL)); err == nil {
		if prefix := strings.TrimSuffix(base.Path, "/"); prefix != "" &&
			strings.HasPrefix(orig.Path, prefix) {
			orig.Path = strings.TrimPrefix(orig.Path, prefix)
			if !strings.HasPrefix(orig.Path, "/") {
				orig.Path = "/" + orig.Path
			}
		}
	}
	orig.Scheme = t.Scheme
	orig.Host = t.Host
	return orig.String()
}

// gpustackAffinityShouldFallback 判断直连的这次结果是否该回退到网关重试。
//
// 回退「路由/可用性」这一类：连接层失败，以及 404 / 502 / 503 / 504。
// 404 必须在内——它是路径或实例不对的信号（service.GPUStackAffinityShouldInvalidate
// 也是这么归类的），而 404 又落在外层 AutomaticRetryStatusCodeRanges（401-407）里，
// 不在这里兜住就会白烧一次换渠道重试。
//
// 4xx 的其余部分与 500 不回退：那是请求本身或引擎内部的问题，换成网关打过去会
// 同样失败，只是把用户的等待和我们的算力都翻一倍。
func gpustackAffinityShouldFallback(resp *http.Response, err error) bool {
	if err != nil {
		return true
	}
	if resp == nil {
		return true
	}
	switch resp.StatusCode {
	case http.StatusNotFound,
		http.StatusBadGateway,
		http.StatusServiceUnavailable,
		http.StatusGatewayTimeout:
		return true
	}
	return false
}

// gpustackAffinityOnDirectFailure 直连失败时的善后：失效实例列表 + 记一行日志。
//
// 失效是必须的，而且必须在**这里**做：回退到网关之后整个请求通常会返回 200，
// 于是 relay 层的 invalidateGPUStackAffinityOnFailure 根本不会被触发，这台死实例
// 会在缓存里停留整个 30 秒 TTL、被反复选中——正是那套失效机制本来要关掉的窗口。
// InvalidateGPUStackInstances 自带 2 秒下限，不会被请求速率打成全量翻页风暴。
//
// 日志同样按窗口节流：实例不可用期间每个落到它的请求都会走到这里。
func gpustackAffinityOnDirectFailure(info *common.RelayInfo, directURL, reason string) {
	if info == nil {
		return
	}
	service.InvalidateGPUStackInstances(info.ChannelId)
	if service.GPUStackAffinityLogAllowed(fmt.Sprintf("direct|%d|%s", info.ChannelId, directURL)) {
		common2.SysError(fmt.Sprintf(
			"gpustack affinity: 直连实例 %s 失败(%s)，本次回退到网关；已失效该渠道的实例列表",
			directURL, reason))
	}
}

// gpustackAffinityDialable 在发请求前用有界超时探一次 TCP。
//
// 见 gpustackAffinityDialTimeout：共享 client 没有拨号超时，黑洞地址会把请求
// 拖到分钟级。这里多付一次同内网握手（亚毫秒）换一个确定的上界。
func gpustackAffinityDialable(target string) bool {
	u, err := url.Parse(target)
	if err != nil || u.Host == "" {
		return false
	}
	conn, err := net.DialTimeout("tcp", u.Host, gpustackAffinityDialTimeout)
	if err != nil {
		return false
	}
	_ = conn.Close()
	return true
}

func DoApiRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	fullRequestURL, err := a.GetRequestURL(info)
	if err != nil {
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	if common2.DebugEnabled {
		println("fullRequestURL:", fullRequestURL)
	}

	// 在 SetupRequestHeader 之后应用 Header Override，确保用户设置优先级最高
	// 这样可以覆盖默认的 Authorization header 设置
	headerOverride, err := processHeaderOverride(info, c)
	if err != nil {
		return nil, err
	}

	build := func(target string, body io.Reader) (*http.Request, error) {
		req, err := http.NewRequest(c.Request.Method, target, body)
		if err != nil {
			return nil, fmt.Errorf("new request failed: %w", err)
		}
		headers := req.Header
		if err := a.SetupRequestHeader(c, &headers, info); err != nil {
			return nil, fmt.Errorf("setup request header failed: %w", err)
		}
		applyHeaderOverrideToRequest(req, headerOverride)
		return req, nil
	}

	directURL := gpustackAffinityRewriteURL(fullRequestURL, info.ChannelBaseUrl, c)
	if directURL != "" && !gpustackAffinityDialable(directURL) {
		// 连不上就别发了：直接走网关，省掉一次注定失败的尝试。同时失效实例列表，
		// 否则这台在 TTL 窗口内会被反复选中。
		gpustackAffinityOnDirectFailure(info, directURL, "拨号失败")
		directURL = ""
	}
	if directURL == "" {
		req, err := build(fullRequestURL, requestBody)
		if err != nil {
			return nil, err
		}
		resp, err := doRequest(c, req, info)
		if err != nil {
			return nil, fmt.Errorf("do request failed: %w", err)
		}
		return resp, nil
	}

	// 走直连：必须把请求体读进内存，否则回退时没有第二份可发（调用方给的是
	// 一次性的 io.Reader）。亲和只作用于 OpenAI 格式的 chat completions，
	// 体积是 JSON 请求体量级，可接受。
	var body []byte
	if requestBody != nil {
		body, err = io.ReadAll(requestBody)
		if err != nil {
			return nil, fmt.Errorf("read request body failed: %w", err)
		}
	}
	newBody := func() io.Reader {
		if body == nil {
			return nil
		}
		return bytes.NewReader(body)
	}

	req, err := build(directURL, newBody())
	if err != nil {
		return nil, err
	}
	resp, err := doRequest(c, req, info)
	if !gpustackAffinityShouldFallback(resp, err) {
		return resp, nil
	}

	// 回退到网关：直连绕过了 ingress 的 proxy-next-upstream 重试策略，所以这一层
	// 必须自己兜。亲和是优化，不该让可用性低于不做亲和。
	reason := "无响应"
	if err != nil {
		reason = err.Error()
	} else if resp != nil {
		reason = fmt.Sprintf("HTTP %d", resp.StatusCode)
		// 回退前把上一次的响应体关掉，否则连接泄漏。
		if resp.Body != nil {
			_ = resp.Body.Close()
		}
	}
	gpustackAffinityOnDirectFailure(info, directURL, reason)

	req, buildErr := build(fullRequestURL, newBody())
	if buildErr != nil {
		return nil, buildErr
	}
	resp, err = doRequest(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	return resp, nil
}

func DoFormRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	fullRequestURL, err := a.GetRequestURL(info)
	if err != nil {
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	if common2.DebugEnabled {
		println("fullRequestURL:", fullRequestURL)
	}
	req, err := http.NewRequest(c.Request.Method, fullRequestURL, requestBody)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	// set form data
	req.Header.Set("Content-Type", c.Request.Header.Get("Content-Type"))
	headers := req.Header
	err = a.SetupRequestHeader(c, &headers, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	// 在 SetupRequestHeader 之后应用 Header Override，确保用户设置优先级最高
	// 这样可以覆盖默认的 Authorization header 设置
	headerOverride, err := processHeaderOverride(info, c)
	if err != nil {
		return nil, err
	}
	applyHeaderOverrideToRequest(req, headerOverride)
	resp, err := doRequest(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	return resp, nil
}

func DoWssRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*websocket.Conn, error) {
	fullRequestURL, err := a.GetRequestURL(info)
	if err != nil {
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	targetHeader := http.Header{}
	err = a.SetupRequestHeader(c, &targetHeader, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	// 在 SetupRequestHeader 之后应用 Header Override，确保用户设置优先级最高
	// 这样可以覆盖默认的 Authorization header 设置
	headerOverride, err := processHeaderOverride(info, c)
	if err != nil {
		return nil, err
	}
	for key, value := range headerOverride {
		targetHeader.Set(key, value)
	}
	targetHeader.Set("Content-Type", c.Request.Header.Get("Content-Type"))
	targetConn, _, err := websocket.DefaultDialer.Dial(fullRequestURL, targetHeader)
	if err != nil {
		return nil, fmt.Errorf("dial failed to %s: %w", fullRequestURL, err)
	}
	// send request body
	//all, err := io.ReadAll(requestBody)
	//err = service.WssString(c, targetConn, string(all))
	return targetConn, nil
}

func startPingKeepAlive(c *gin.Context, pingInterval time.Duration) context.CancelFunc {
	pingerCtx, stopPinger := context.WithCancel(context.Background())

	gopool.Go(func() {
		defer func() {
			// 增加panic恢复处理
			if r := recover(); r != nil {
				if common2.DebugEnabled {
					println("SSE ping goroutine panic recovered:", fmt.Sprintf("%v", r))
				}
			}
			if common2.DebugEnabled {
				println("SSE ping goroutine stopped.")
			}
		}()

		if pingInterval <= 0 {
			pingInterval = helper.DefaultPingInterval
		}

		ticker := time.NewTicker(pingInterval)
		// 确保在任何情况下都清理ticker
		defer func() {
			ticker.Stop()
			if common2.DebugEnabled {
				println("SSE ping ticker stopped")
			}
		}()

		var pingMutex sync.Mutex
		if common2.DebugEnabled {
			println("SSE ping goroutine started")
		}

		// 增加超时控制，防止goroutine长时间运行
		maxPingDuration := 120 * time.Minute // 最大ping持续时间
		pingTimeout := time.NewTimer(maxPingDuration)
		defer pingTimeout.Stop()

		for {
			select {
			// 发送 ping 数据
			case <-ticker.C:
				if err := sendPingData(c, &pingMutex); err != nil {
					if common2.DebugEnabled {
						println("SSE ping error, stopping goroutine:", err.Error())
					}
					return
				}
			// 收到退出信号
			case <-pingerCtx.Done():
				return
			// request 结束
			case <-c.Request.Context().Done():
				return
			// 超时保护，防止goroutine无限运行
			case <-pingTimeout.C:
				if common2.DebugEnabled {
					println("SSE ping goroutine timeout, stopping")
				}
				return
			}
		}
	})

	return stopPinger
}

func sendPingData(c *gin.Context, mutex *sync.Mutex) error {
	// 增加超时控制，防止锁死等待
	done := make(chan error, 1)
	go func() {
		mutex.Lock()
		defer mutex.Unlock()

		err := helper.PingData(c)
		if err != nil {
			logger.LogError(c, "SSE ping error: "+err.Error())
			done <- err
			return
		}

		if common2.DebugEnabled {
			println("SSE ping data sent.")
		}
		done <- nil
	}()

	// 设置发送ping数据的超时时间
	select {
	case err := <-done:
		return err
	case <-time.After(10 * time.Second):
		return errors.New("SSE ping data send timeout")
	case <-c.Request.Context().Done():
		return errors.New("request context cancelled during ping")
	}
}

func DoRequest(c *gin.Context, req *http.Request, info *common.RelayInfo) (*http.Response, error) {
	return doRequest(c, req, info)
}
func doRequest(c *gin.Context, req *http.Request, info *common.RelayInfo) (*http.Response, error) {
	var client *http.Client
	var err error
	if info.ChannelSetting.Proxy != "" {
		client, err = service.NewProxyHttpClient(info.ChannelSetting.Proxy)
		if err != nil {
			return nil, fmt.Errorf("new proxy http client failed: %w", err)
		}
	} else {
		client = service.GetHttpClient()
	}

	var stopPinger context.CancelFunc
	if info.IsStream {
		helper.SetEventStreamHeaders(c)
		// 处理流式请求的 ping 保活
		generalSettings := operation_setting.GetGeneralSetting()
		if generalSettings.PingIntervalEnabled && !info.DisablePing {
			pingInterval := time.Duration(generalSettings.PingIntervalSeconds) * time.Second
			stopPinger = startPingKeepAlive(c, pingInterval)
			// 使用defer确保在任何情况下都能停止ping goroutine
			defer func() {
				if stopPinger != nil {
					stopPinger()
					if common2.DebugEnabled {
						println("SSE ping goroutine stopped by defer")
					}
				}
			}()
		}
	}

	resp, err := client.Do(req)
	if err != nil {
		logger.LogError(c, "do request failed: "+err.Error())
		return nil, types.NewError(err, types.ErrorCodeDoRequestFailed, types.ErrOptionWithHideErrMsg("upstream error: do request failed"))
	}
	if resp == nil {
		return nil, errors.New("resp is nil")
	}

	_ = req.Body.Close()
	_ = c.Request.Body.Close()
	return resp, nil
}

func DoTaskApiRequest(a TaskAdaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	fullRequestURL, err := a.BuildRequestURL(info)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequest(c.Request.Method, fullRequestURL, requestBody)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	req.GetBody = func() (io.ReadCloser, error) {
		return io.NopCloser(requestBody), nil
	}

	err = a.BuildRequestHeader(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	resp, err := doRequest(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	return resp, nil
}
